### ISSUE TITLE
Certain filetypes cause g:cosco_whitelist errors when g:cosco_whitelist isn't set explicitly

### ISSUE THREAD

**Issue by MultisampledNight** [TornaxO7/cosco.vim#1]
When `g:cosco_whitelist` isn't set in my `init.vim`, it causes an error when opening certain filetypes such as `diff` or `git` (achievable through `git diff` and `git log`):
```vim
Error detected while processing function cosco_helpers#ActivateCosco[2]..cosco_helpers#FiletypeInWhitelist:
line    3:
E121: Undefined variable: g:cosco_whitelist
E15: Invalid expression: g:cosco_whitelist
E121: Undefined variable: g:cosco_whitelist
E15: Invalid expression: g:cosco_whitelist
Error detected while processing function <SNR>23_enableCosco:
line    3:
E121: Undefined variable: g:cosco_whitelist
Press ENTER or type command to continue
Error detected while processing function <SNR>23_enableCosco:
line    3:
E116: Invalid arguments for function index
Press ENTER or type command to continue
Error detected while processing function <SNR>23_enableCosco:
line    3:
E15: Invalid expression: !exists("g:cosco_enable") && index(g:cosco_whitelist, &ft) != -1
Press ENTER or type command to continue
```
A GIF to illustrate the process:
![cosco-unset-whitelist-errors](https://user-images.githubusercontent.com/80128916/116827302-9221cf00-ab98-11eb-8709-993daed56942.gif)

This bug doesn't appear when `g:cosco_whitelist` is set manually in the user's init.vim. A default is supposed to jump in when `g:cosco_whitellist` isn't set, but this seems to fail.

**Comment by TornaxO7** [comment]
Thank you for the issue report! Could you please create a mp4 file? Otherwise I always have to wait until the GIF repeats itself which can get a little bit annoying...

**Comment by MultisampledNight** [comment]
~~Just do it yourself using ffmpeg~~
Here you go: 
https://user-images.githubusercontent.com/80128916/116845605-89f08080-abe6-11eb-92ee-83cc7304b425.mp4

**Comment by TornaxO7** [comment]
Does it work now?

**Comment by MultisampledNight** [comment]
Yes, it works now. Thanks!
